# This is a basic workflow to help you get started with Actions

name: 'Update Bot'
 
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * 1'

# ┌───────────── minute (0 - 59)
# │ ┌───────────── hour (0 - 23)
# │ │ ┌───────────── day of the month (1 - 31)
# │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
# │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
# │ │ │ │ │
# │ │ │ │ │
# │ │ │ │ │
# * * * * *
# 0 0 * * 1

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Print server time'
        run: |
          echo '当前服务器系统时间'
          echo $(date +%F%n%T)
      - name: 'Checkout Ubuntu'
        uses: actions/checkout@v1
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: 'Install dependencies'
        run: pip install requests
      - name: 'update'
        run: python3 ./update.py
      - name: 'commit'
        run: |
          git config --global user.email zphiliam@users.noreply.github.com
          git config --global user.name zphiliam
          git add *
          git commit -m "update by bot"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
